spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**    #静态资源的请求方式
    resources:
      static-locations: classpath:/static/  # 静态资源的配置位置，可以写成一个数组配置多个目录