spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    data-username: root
    data-password: 123456
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: warn
    com.stone: info
  file:
    path: log/bog-pro.log

server:
  port: 8081